---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mirror-images
  labels:
    app: mirror-images
spec:
  schedule: '@daily'
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mirror-images
        spec:
          containers:
            - name: mirror-images
              image: image-registry.openshift-image-registry.svc:5000/samba/mirror-images:latest
              env:
                - name: DOCKER_CONFIG_JSON
                  valueFrom:
                    secretKeyRef:
                      name: sambabot-docker-io
                      key: .dockerconfigjson
                - name: CI_REGISTRY_USER
                  valueFrom:
                    secretKeyRef:
                      name: container-registry-auth
                      key: username
                - name: CI_REGISTRY_PASSWD
                  valueFrom:
                    secretKeyRef:
                      name: container-registry-auth
                      key: password
          restartPolicy: OnFailure
