name: Deploy Jenkins jobs
on:
  push:
    branches:
      - main

jobs:
  push:
    name: Deploy Jenkins jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build JJB container image
        run: docker build -t samba-centosci -f deploy/Dockerfile .
      - name: update Jenkins Jobs
        run: docker run --rm --env="JENKINS_API_KEY=${{ secrets.JENKINS_API_KEY }}" --entrypoint=deploy/deploy-jobs.sh samba-centosci:latest
