name: Verification of Jenkins jobs
on:
  pull_request:
    branches:
      - '*'

jobs:
  pull_request:
    name: Verify Jenkins jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build JJB container image
        run: docker build -t samba-centosci -f deploy/Dockerfile .
      - name: run YAML verification using built JJB container image
        run: docker run --rm samba-centosci:latest
